[package]
name = "hello_flappy"
version = "0.1.0"
edition = "2018"
authors = ["Josep Calull"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
rand = "0.8.0"